stages:
  split:
    cmd: /home/ubuntu/exam_DVC/.monenv/bin/python  src/data/split_data.py
    deps:
    - data/raw_data
    - src/data/split_data.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: /home/ubuntu/exam_DVC/.monenv/bin/python  src/data/scale_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
    - src/data/scale_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: /home/ubuntu/exam_DVC/.monenv/bin/python src/models/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: /home/ubuntu/exam_DVC/.monenv/bin/python src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: /home/ubuntu/exam_DVC/.monenv/bin/python src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/model.pkl
    - src/models/evaluate_model.py
    metrics:
    - metrics/scores.json:
        cache: false
